Pkg.update()
Pkg.clone("https://github.com/essenciary/Genie.jl")
Pkg.clone("https://github.com/JuliaDB/DBI.jl")
Pkg.clone("https://github.com/JuliaDB/PostgreSQL.jl")
Pkg.clone("https://github.com/essenciary/Flax.jl")
Pkg.clone("https://github.com/essenciary/SearchLight.jl")
