FROM julia:0.6

RUN apt-get update \
    && apt-get upgrade -y -o Dpkg::Options::="--force-confdef" -o DPkg::Options::="--force-confold" \
    && apt-get install -y \
    man-db \
    libc6 \
    libc6-dev \
    build-essential \
    wget \
    curl \
    file \
    vim \
    screen \
    tmux \
    unzip \
    pkg-config \
    cmake \
    && apt-get clean

ADD deps.jl deps.jl
RUN julia deps.jl

ADD app /app

WORKDIR /app

CMD ["bin/server"]
